apiVersion: v1
# Kind for service
kind: Service
metadata:
  # Name your service
  name: demo
  labels:
    app: demo
spec:
  # Choose how to expose your service
  type: ClusterIP
  ports:
    # The port number to expose the service
    - port: 8080
  # Pod to route service traffic  
  selector:
    app: demo
