apiVersion: v1
# Kind for kubernets ConfigMap
kind: ConfigMap
metadata:
  # Name your ConfigMap
  name: db-secret-credentials
  labels:
    app: postgres
data:
  # User DB
  POSTGRES_DB: demo
  # Db user
  POSTGRES_USER: postgres
  # Db password
  POSTGRES_PASSWORD: password
